name: Release

on:
  workflow_dispatch:

jobs:
  debug-mima:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Debug Mima - why does it see etag-caching classes?!?
        run: sbt "show core / versionPolicyFindMimaIssues"
  release:
    uses: guardian/gha-scala-library-release-workflow/.github/workflows/reusable-release.yml@main
    permissions: { contents: write }
    with:
      SONATYPE_PROFILE_NAME: 'com.madgag'
      SONATYPE_CREDENTIAL_HOST: 's01.oss.sonatype.org'
      SONATYPE_USERNAME: 'roberto'
    secrets:
      SONATYPE_PASSWORD: ${{ secrets.AUTOMATED_MAVEN_RELEASE_SONATYPE_PASSWORD }}
      PGP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_SECRET }}
